name: composer update

on:
  push:
#    branches:
#      - master
  #    - v*
  schedule:
    - cron: '0 4 * * *' #UTC

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: composer update action
        uses: kawax/composer-update-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          COMPOSER_PATH: /update
          GIT_NAME: 'github-actions[bot]'
          GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
